import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}", "./lib/**/*.{js,ts,jsx,tsx,mdx}"],
  safelist: [
    '-mt-24',
    '-mt-28',
    '-mt-32',
    'mt-[-100px]',
    '-mt-[100px]',
    '-mt-[96px]',
    // Add responsive variants
    'md:-mt-24',
    'md:-mt-28',
    'md:-mt-32',
    'md:mt-[-100px]',
    'md:mt-[100px]',
    'md:-mt-[96px]',
    'lg:-mt-24',
    'lg:-mt-28',
    'lg:-mt-32',
    // Float layout utilities
    'float-left',
    'float-right',
    'float-none',
    'max-xs:float-none',
    'max-xs:w-full',
    'max-xs:mx-0',
    'max-xs:mb-4',
    'max-md:float-none',
    'max-md:w-full',
    'max-md:mx-0',
    'max-md:mb-4',
    'max-lg:float-none',
    'max-lg:w-full',
    'max-lg:mx-0',
    'max-lg:mb-4',
    'max-xl:float-none',
    'max-xl:w-full',
    'max-xl:mx-0',
    'max-xl:mb-4',
    // Display visibility utilities
    'hide-above-xs',
    'hide-below-xs',
    'hide-above-sm',
    'hide-below-sm',
    'hide-above-md',
    'hide-below-md',
    'hide-above-lg',
    'hide-below-lg',
    'hide-above-xl',
    'hide-below-xl',
    // Responsive content utilities
    'xs-short-lineheight',
    'xs-small-margin',
    // Font family classes for digital card title typography
    'font-sans',
    'font-serif',
    'font-mono',
    'font-georgia',
    'font-playfair',
    'font-merriweather',
    'font-montserrat',
    'font-roboto',
    'font-lato',
    'font-red-hat-display',
    'font-corsiva',
    // Font weight classes
    'font-thin',
    'font-extralight',
    'font-light',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-extrabold',
    'font-black',
    // Text color classes for typography settings
    'text-gray-900',
    'text-gray-800',
    'text-gray-700',
    'text-gray-600',
    'text-gray-500',
    'text-gray-400',
    'text-gray-300',
    'text-white',
    'text-black',
    'text-glamlink-teal',
    'text-glamlink-purple',
    'text-blue-600',
    'text-blue-500',
    'text-green-600',
    'text-green-500',
    'text-red-600',
    'text-red-500',
    'text-yellow-600',
    'text-yellow-500',
    'text-purple-600',
    'text-purple-500',
    'text-teal-600',
    'text-teal-500',
    'text-indigo-600',
    'text-pink-600',
    // Font size classes (static)
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',
    // Responsive font size classes
    'md:text-base',
    'md:text-lg',
    'md:text-xl',
    'md:text-2xl',
    'md:text-3xl',
    'md:text-4xl',
    'md:text-5xl',
    'md:text-6xl',
    // Text alignment classes
    'text-left',
    'text-center',
    'text-right',
  ],
  theme: {
    extend: {
      screens: {
        xs: "475px",
        "lg-custom": "992px",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Glamlink colors
        glamlink: {
          teal: "#22B8C8",
          "teal-dark": "#1A8F9C",
          "teal-light": "#4AC7D5",
          purple: "#9333EA",
          gray: {
            50: "#F9FAFB",
            100: "#F3F4F6",
            200: "#E5E7EB",
            300: "#D1D5DB",
            400: "#9CA3AF",
            500: "#6B7280",
            600: "#4B5563",
            700: "#374151",
            800: "#1F2937",
            900: "#111827",
          },
        },
      },
      fontFamily: {
        // Base fonts
        sans: ["var(--font-roboto)", "Roboto", "sans-serif"],
        serif: ["Georgia", "serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
        // Named fonts for explicit use
        roboto: ["var(--font-roboto)", "Roboto", "sans-serif"],
        geist: ["var(--font-geist-sans)", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        // Google Fonts for digital card title typography
        georgia: ["Georgia", "serif"],
        playfair: ["var(--font-playfair)", "Playfair Display", "serif"],
        merriweather: ["var(--font-merriweather)", "Merriweather", "serif"],
        montserrat: ["var(--font-montserrat)", "Montserrat", "sans-serif"],
        lato: ["var(--font-lato)", "Lato", "sans-serif"],
        "red-hat-display": ["var(--font-red-hat-display)", "Red Hat Display", "sans-serif"],
        // Decorative/script fonts (system fonts)
        corsiva: ["Monotype Corsiva", "cursive"],
      },
      animation: {
        "fade-in": "fadeIn 0.6s ease-in-out",
        "slide-up": "slideUp 0.6s ease-out",
        "scale-in": "scaleIn 0.4s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      lineClamp: {
        3: "3",
      },
      fontSize: {
        "sm-custom": "1rem", // 16px for navigation links
        base: "1em", // 1em (relative to parent) instead of default 16px
        xl: "1.5rem", // 24px instead of default 20px
      },
    },
  },
  darkMode: "class",
  plugins: [],
};

export default config;
